/**
 * Source of truth for tasks across the app.
 * Linked to project IDs (projectData.js) and user IDs (userData.js).
 */

export const CURRENT_USER_ID = 'usr-ahsan';

export const TASK_STATUSES = ['todo', 'in-progress', 'in-review', 'done'];

export const TASK_STATUS_META = {
  todo: {
    label: 'To Do',
    tone: 'bg-slate-100 text-slate-600 ring-slate-300/50',
    column: 'from-slate-50 to-white',
  },
  'in-progress': {
    label: 'In Progress',
    tone: 'bg-blue-50 text-primary ring-primary/15',
    column: 'from-[#EFF6FF]/80 to-white',
  },
  'in-review': {
    label: 'In Review',
    tone: 'bg-violet-50 text-violet-700 ring-violet-500/15',
    column: 'from-violet-50/60 to-white',
  },
  done: {
    label: 'Done',
    tone: 'bg-emerald-50 text-emerald-700 ring-emerald-500/15',
    column: 'from-emerald-50/50 to-white',
  },
};

function sub(id, title, done = false) {
  return { id, title, done };
}

function comment(id, userId, userName, initials, text, time) {
  return { id, userId, userName, initials, text, time };
}

export const TASKS = [
  // AI Company Brain Core
  {
    id: 'tsk-001',
    title: 'Build Projects list & board views',
    description: 'Ship grid + kanban views for the Projects module with filters and load more.',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-eng',
    departmentName: 'Engineering',
    assigneeId: 'usr-raza',
    assigneeName: 'M. Raza',
    assigneeInitials: 'MR',
    createdById: 'usr-ahsan',
    createdByName: 'Ahsan Taqweem',
    status: 'in-progress',
    priority: 'urgent',
    dueDate: '2026-07-28',
    createdAt: '2026-07-18',
    subtasks: [
      sub('s1', 'Grid cards', true),
      sub('s2', 'Board columns', true),
      sub('s3', 'Filter bar', false),
    ],
    comments: [
      comment('c1', 'usr-sara', 'Sara Khan', 'SK', 'Looks great — can we match Linear’s empty column state?', '1h ago'),
      comment('c2', 'usr-raza', 'M. Raza', 'MR', 'On it after filters land.', '40m ago'),
    ],
    attachments: [{ id: 'f1', name: 'board-spec.pdf', size: '240 KB' }],
  },
  {
    id: 'tsk-002',
    title: 'Wire department cross-links',
    description: 'Connect Department Detail Projects tab to projectData filters.',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-eng',
    departmentName: 'Engineering',
    assigneeId: 'usr-omar',
    assigneeName: 'Omar Farooq',
    assigneeInitials: 'OF',
    createdById: 'usr-raza',
    createdByName: 'M. Raza',
    status: 'todo',
    priority: 'high',
    dueDate: '2026-07-29',
    createdAt: '2026-07-20',
    subtasks: [sub('s1', 'Import helpers'), sub('s2', 'Render ProjectCards')],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-003',
    title: 'Design project workspace header',
    description: 'Header with breadcrumbs, badges, avatars, and progress.',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-design',
    departmentName: 'Design',
    assigneeId: 'usr-lina',
    assigneeName: 'Lina Noor',
    assigneeInitials: 'LN',
    createdById: 'usr-sara',
    createdByName: 'Sara Khan',
    status: 'done',
    priority: 'medium',
    dueDate: '2026-07-20',
    createdAt: '2026-07-10',
    subtasks: [sub('s1', 'Figma frame', true), sub('s2', 'Hand off tokens', true)],
    comments: [
      comment('c1', 'usr-ahsan', 'Ahsan Taqweem', 'AT', 'Shipped — looks premium.', '5d ago'),
    ],
    attachments: [{ id: 'f1', name: 'header.fig', size: '1.2 MB' }],
  },
  {
    id: 'tsk-004',
    title: 'Product review of milestone UX',
    description: 'Review milestone list interactions before Tasks module launch.',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-product',
    departmentName: 'Product',
    assigneeId: 'usr-sara',
    assigneeName: 'Sara Khan',
    assigneeInitials: 'SK',
    createdById: 'usr-ahsan',
    createdByName: 'Ahsan Taqweem',
    status: 'in-review',
    priority: 'high',
    dueDate: '2026-07-27',
    createdAt: '2026-07-21',
    subtasks: [sub('s1', 'Walkthrough notes', true), sub('s2', 'Share feedback', false)],
    comments: [
      comment('c1', 'usr-lina', 'Lina Noor', 'LN', 'Check done-state strike-through contrast.', '3h ago'),
    ],
    attachments: [],
  },
  {
    id: 'tsk-005',
    title: 'Security checklist for project files tab',
    description: 'Define ACL notes for future Files tab on Project Detail.',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-eng',
    departmentName: 'Engineering',
    assigneeId: 'usr-ahsan',
    assigneeName: 'Ahsan Taqweem',
    assigneeInitials: 'AT',
    createdById: 'usr-ahsan',
    createdByName: 'Ahsan Taqweem',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-08-02',
    createdAt: '2026-07-22',
    subtasks: [sub('s1', 'List sensitive file types'), sub('s2', 'Draft policy')],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-006',
    title: 'Promote tasks into standalone module',
    description: 'Create taskData as source of truth and migrate Project Tasks tab.',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-eng',
    departmentName: 'Engineering',
    assigneeId: 'usr-ahsan',
    assigneeName: 'Ahsan Taqweem',
    assigneeInitials: 'AT',
    createdById: 'usr-raza',
    createdByName: 'M. Raza',
    status: 'in-progress',
    priority: 'urgent',
    dueDate: '2026-07-26',
    createdAt: '2026-07-24',
    subtasks: [
      sub('s1', 'taskData.js', true),
      sub('s2', 'Tasks page', false),
      sub('s3', 'Detail drawer', false),
    ],
    comments: [
      comment('c1', 'usr-raza', 'M. Raza', 'MR', 'Keep Linear-style peek drawer.', '2h ago'),
    ],
    attachments: [],
  },

  // API Gateway
  {
    id: 'tsk-007',
    title: 'Implement token bucket limiter',
    description: 'Rate limiting middleware for multi-tenant gateway routes.',
    projectId: 'prj-api-gw',
    projectName: 'API Gateway v2',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-eng',
    departmentName: 'Engineering',
    assigneeId: 'usr-omar',
    assigneeName: 'Omar Farooq',
    assigneeInitials: 'OF',
    createdById: 'usr-raza',
    createdByName: 'M. Raza',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2026-07-30',
    createdAt: '2026-07-15',
    subtasks: [sub('s1', 'Unit tests', false), sub('s2', 'Redis store', true)],
    comments: [],
    attachments: [{ id: 'f1', name: 'limiter-rfc.md', size: '18 KB' }],
  },
  {
    id: 'tsk-008',
    title: 'Add OpenTelemetry traces',
    description: 'Instrument gateway spans for request path and tenant id.',
    projectId: 'prj-api-gw',
    projectName: 'API Gateway v2',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-eng',
    departmentName: 'Engineering',
    assigneeId: 'usr-raza',
    assigneeName: 'M. Raza',
    assigneeInitials: 'MR',
    createdById: 'usr-ahsan',
    createdByName: 'Ahsan Taqweem',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-08-05',
    createdAt: '2026-07-16',
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-009',
    title: 'Document tenant routing',
    description: 'Write docs for path- and header-based tenant resolution.',
    projectId: 'prj-api-gw',
    projectName: 'API Gateway v2',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-eng',
    departmentName: 'Engineering',
    assigneeId: 'usr-raza',
    assigneeName: 'M. Raza',
    assigneeInitials: 'MR',
    createdById: 'usr-raza',
    createdByName: 'M. Raza',
    status: 'done',
    priority: 'low',
    dueDate: '2026-07-12',
    createdAt: '2026-07-01',
    subtasks: [sub('s1', 'Draft', true), sub('s2', 'Publish', true)],
    comments: [],
    attachments: [],
  },

  // Design System
  {
    id: 'tsk-010',
    title: 'Document color tokens',
    description: 'Publish @theme token reference for Inter + primary palette.',
    projectId: 'prj-design-sys',
    projectName: 'Design System 2.0',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-design',
    departmentName: 'Design',
    assigneeId: 'usr-lina',
    assigneeName: 'Lina Noor',
    assigneeInitials: 'LN',
    createdById: 'usr-lina',
    createdByName: 'Lina Noor',
    status: 'done',
    priority: 'medium',
    dueDate: '2026-07-05',
    createdAt: '2026-06-20',
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-011',
    title: 'Motion spring presets',
    description: 'Catalog Framer Motion spring values used across overlays.',
    projectId: 'prj-design-sys',
    projectName: 'Design System 2.0',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-design',
    departmentName: 'Design',
    assigneeId: 'usr-lina',
    assigneeName: 'Lina Noor',
    assigneeInitials: 'LN',
    createdById: 'usr-sara',
    createdByName: 'Sara Khan',
    status: 'in-progress',
    priority: 'medium',
    dueDate: '2026-07-31',
    createdAt: '2026-07-08',
    subtasks: [sub('s1', 'Drawer springs', true), sub('s2', 'Card hover', false)],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-012',
    title: 'Review with Product',
    description: 'Align design system roadmap with Q3 product bets.',
    projectId: 'prj-design-sys',
    projectName: 'Design System 2.0',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-product',
    departmentName: 'Product',
    assigneeId: 'usr-sara',
    assigneeName: 'Sara Khan',
    assigneeInitials: 'SK',
    createdById: 'usr-lina',
    createdByName: 'Lina Noor',
    status: 'todo',
    priority: 'low',
    dueDate: '2026-08-08',
    createdAt: '2026-07-19',
    subtasks: [],
    comments: [],
    attachments: [],
  },

  // People Ops
  {
    id: 'tsk-013',
    title: 'Welcome email templates',
    description: 'Finalize onboarding welcome series copy.',
    projectId: 'prj-onboarding',
    projectName: 'People Ops Onboarding',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-hr',
    departmentName: 'HR',
    assigneeId: 'usr-hira',
    assigneeName: 'Hira Ali',
    assigneeInitials: 'HA',
    createdById: 'usr-hira',
    createdByName: 'Hira Ali',
    status: 'done',
    priority: 'low',
    dueDate: '2026-06-20',
    createdAt: '2026-05-01',
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-014',
    title: 'Manager approval flow UI',
    description: 'Static UI for manager approvals on onboarding checklist.',
    projectId: 'prj-onboarding',
    projectName: 'People Ops Onboarding',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-hr',
    departmentName: 'HR',
    assigneeId: 'usr-hira',
    assigneeName: 'Hira Ali',
    assigneeInitials: 'HA',
    createdById: 'usr-sara',
    createdByName: 'Sara Khan',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2026-08-10',
    createdAt: '2026-07-01',
    subtasks: [sub('s1', 'Wireframes', true), sub('s2', 'Build screens', false)],
    comments: [
      comment('c1', 'usr-sara', 'Sara Khan', 'SK', 'Keep it consistent with Invite User modal.', '1d ago'),
    ],
    attachments: [],
  },

  // Harbor
  {
    id: 'tsk-015',
    title: 'Alert thresholds for freezers',
    description: 'Define temperature alert bands for cold chain hubs.',
    projectId: 'prj-cold-chain',
    projectName: 'Cold Chain Hub',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Logistics',
    departmentId: 'dept-harbor-ops',
    departmentName: 'Operations',
    assigneeId: 'usr-bilal',
    assigneeName: 'Bilal Ahmed',
    assigneeInitials: 'BA',
    createdById: 'usr-nadia',
    createdByName: 'Nadia Rehman',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2026-08-01',
    createdAt: '2026-07-05',
    subtasks: [sub('s1', 'Sensor calibration', true), sub('s2', 'Alert copy', false)],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-016',
    title: 'Fleet assignment rules',
    description: 'Rules engine sketch for assigning refrigerated trucks.',
    projectId: 'prj-cold-chain',
    projectName: 'Cold Chain Hub',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Logistics',
    departmentId: 'dept-harbor-ops',
    departmentName: 'Operations',
    assigneeId: 'usr-usman',
    assigneeName: 'Usman Tariq',
    assigneeInitials: 'UT',
    createdById: 'usr-bilal',
    createdByName: 'Bilal Ahmed',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-08-12',
    createdAt: '2026-07-10',
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-017',
    title: 'Executive weekly digest',
    description: 'Automated capacity digest for leadership.',
    projectId: 'prj-cold-chain',
    projectName: 'Cold Chain Hub',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Logistics',
    departmentId: 'dept-harbor-exec',
    departmentName: 'Executive',
    assigneeId: 'usr-nadia',
    assigneeName: 'Nadia Rehman',
    assigneeInitials: 'NR',
    createdById: 'usr-nadia',
    createdByName: 'Nadia Rehman',
    status: 'done',
    priority: 'low',
    dueDate: '2026-07-01',
    createdAt: '2026-06-15',
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-018',
    title: 'Compile site criteria',
    description: 'Site selection criteria for expansion map.',
    projectId: 'prj-harbor-exp',
    projectName: 'Regional Expansion Map',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Logistics',
    departmentId: 'dept-harbor-exec',
    departmentName: 'Executive',
    assigneeId: 'usr-nadia',
    assigneeName: 'Nadia Rehman',
    assigneeInitials: 'NR',
    createdById: 'usr-nadia',
    createdByName: 'Nadia Rehman',
    status: 'done',
    priority: 'medium',
    dueDate: '2026-06-20',
    createdAt: '2026-06-02',
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-019',
    title: 'Ops capacity model',
    description: 'Model hub throughput for candidate sites.',
    projectId: 'prj-harbor-exp',
    projectName: 'Regional Expansion Map',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Logistics',
    departmentId: 'dept-harbor-ops',
    departmentName: 'Operations',
    assigneeId: 'usr-bilal',
    assigneeName: 'Bilal Ahmed',
    assigneeInitials: 'BA',
    createdById: 'usr-nadia',
    createdByName: 'Nadia Rehman',
    status: 'todo',
    priority: 'high',
    dueDate: '2026-08-20',
    createdAt: '2026-07-02',
    subtasks: [sub('s1', 'Data pull'), sub('s2', 'Spreadsheet model')],
    comments: [],
    attachments: [],
  },

  // Pulse
  {
    id: 'tsk-020',
    title: 'Triage priority rules',
    description: 'Clinical triage priority matrix for intake.',
    projectId: 'prj-patient-intake',
    projectName: 'Patient Intake Digitization',
    organizationId: 'org-pulse',
    organizationName: 'Pulse Health Group',
    departmentId: 'dept-pulse-clinical',
    departmentName: 'Clinical',
    assigneeId: 'usr-amna',
    assigneeName: 'Dr. Amna Siddiqui',
    assigneeInitials: 'AS',
    createdById: 'usr-amna',
    createdByName: 'Dr. Amna Siddiqui',
    status: 'in-progress',
    priority: 'high',
    dueDate: '2026-08-05',
    createdAt: '2026-07-01',
    subtasks: [sub('s1', 'Draft rules', true), sub('s2', 'Peer review', false)],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-021',
    title: 'HIPAA checklist for IT',
    description: 'Security checklist before Clinic A pilot.',
    projectId: 'prj-patient-intake',
    projectName: 'Patient Intake Digitization',
    organizationId: 'org-pulse',
    organizationName: 'Pulse Health Group',
    departmentId: 'dept-pulse-it',
    departmentName: 'IT',
    assigneeId: 'usr-kamran',
    assigneeName: 'Kamran Shah',
    assigneeInitials: 'KS',
    createdById: 'usr-amna',
    createdByName: 'Dr. Amna Siddiqui',
    status: 'in-review',
    priority: 'urgent',
    dueDate: '2026-07-28',
    createdAt: '2026-07-12',
    subtasks: [sub('s1', 'Encryption review', true), sub('s2', 'Access logs', true)],
    comments: [
      comment('c1', 'usr-amna', 'Dr. Amna Siddiqui', 'AS', 'Please confirm MFA coverage.', '6h ago'),
    ],
    attachments: [{ id: 'f1', name: 'hipaa-checklist.xlsx', size: '86 KB' }],
  },
  {
    id: 'tsk-022',
    title: 'Admin MFA policy',
    description: 'Policy document for admin MFA enforcement.',
    projectId: 'prj-mfa-rollout',
    projectName: 'Clinic MFA Rollout',
    organizationId: 'org-pulse',
    organizationName: 'Pulse Health Group',
    departmentId: 'dept-pulse-it',
    departmentName: 'IT',
    assigneeId: 'usr-kamran',
    assigneeName: 'Kamran Shah',
    assigneeInitials: 'KS',
    createdById: 'usr-kamran',
    createdByName: 'Kamran Shah',
    status: 'done',
    priority: 'urgent',
    dueDate: '2026-05-01',
    createdAt: '2026-03-01',
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-023',
    title: 'Clinician training pack',
    description: 'Training materials for MFA enrollment.',
    projectId: 'prj-mfa-rollout',
    projectName: 'Clinic MFA Rollout',
    organizationId: 'org-pulse',
    organizationName: 'Pulse Health Group',
    departmentId: 'dept-pulse-clinical',
    departmentName: 'Clinical',
    assigneeId: 'usr-amna',
    assigneeName: 'Dr. Amna Siddiqui',
    assigneeInitials: 'AS',
    createdById: 'usr-kamran',
    createdByName: 'Kamran Shah',
    status: 'done',
    priority: 'medium',
    dueDate: '2026-06-15',
    createdAt: '2026-04-10',
    subtasks: [],
    comments: [],
    attachments: [],
  },

  // Ledger
  {
    id: 'tsk-024',
    title: 'Gather bank reconciliations',
    description: 'Collect Q2 bank reconciliations for audit evidence.',
    projectId: 'prj-q2-audit',
    projectName: 'Q2 Compliance Audit',
    organizationId: 'org-ledger',
    organizationName: 'Ledger & Co.',
    departmentId: 'dept-ledger-finance',
    departmentName: 'Finance',
    assigneeId: 'usr-mehwish',
    assigneeName: 'Mehwish Rauf',
    assigneeInitials: 'MR',
    createdById: 'usr-imran',
    createdByName: 'Imran Qureshi',
    status: 'done',
    priority: 'high',
    dueDate: '2026-05-15',
    createdAt: '2026-04-20',
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-025',
    title: 'Guest auditor access',
    description: 'Provision read-only access for Zain Malik.',
    projectId: 'prj-q2-audit',
    projectName: 'Q2 Compliance Audit',
    organizationId: 'org-ledger',
    organizationName: 'Ledger & Co.',
    departmentId: 'dept-ledger-finance',
    departmentName: 'Finance',
    assigneeId: 'usr-zain',
    assigneeName: 'Zain Malik',
    assigneeInitials: 'ZM',
    createdById: 'usr-mehwish',
    createdByName: 'Mehwish Rauf',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-08-01',
    createdAt: '2026-07-18',
    subtasks: [sub('s1', 'Invite accepted'), sub('s2', 'Folder ACL')],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-026',
    title: 'Partner sign-off',
    description: 'Final partner sign-off on audit package.',
    projectId: 'prj-q2-audit',
    projectName: 'Q2 Compliance Audit',
    organizationId: 'org-ledger',
    organizationName: 'Ledger & Co.',
    departmentId: 'dept-ledger-finance',
    departmentName: 'Finance',
    assigneeId: 'usr-imran',
    assigneeName: 'Imran Qureshi',
    assigneeInitials: 'IQ',
    createdById: 'usr-mehwish',
    createdByName: 'Mehwish Rauf',
    status: 'todo',
    priority: 'high',
    dueDate: '2026-08-04',
    createdAt: '2026-07-20',
    subtasks: [],
    comments: [],
    attachments: [],
  },

  // Summit
  {
    id: 'tsk-027',
    title: 'Landing page A/B test',
    description: 'Run A/B test for Ramadan campaign landing.',
    projectId: 'prj-ramadan',
    projectName: 'Ramadan Campaign Board',
    organizationId: 'org-summit',
    organizationName: 'Summit Retail Group',
    departmentId: 'dept-summit-mkt',
    departmentName: 'Marketing',
    assigneeId: 'usr-noor',
    assigneeName: 'Noor Hassan',
    assigneeInitials: 'NH',
    createdById: 'usr-fahad',
    createdByName: 'Fahad Mirza',
    status: 'in-progress',
    priority: 'urgent',
    dueDate: '2026-03-10',
    createdAt: '2026-02-20',
    subtasks: [sub('s1', 'Variants', true), sub('s2', 'Analyze', false)],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-028',
    title: 'Store POS checklist',
    description: 'Align store POS checklist with campaign ops.',
    projectId: 'prj-ramadan',
    projectName: 'Ramadan Campaign Board',
    organizationId: 'org-summit',
    organizationName: 'Summit Retail Group',
    departmentId: 'dept-summit-exec',
    departmentName: 'Executive',
    assigneeId: 'usr-fahad',
    assigneeName: 'Fahad Mirza',
    assigneeInitials: 'FM',
    createdById: 'usr-noor',
    createdByName: 'Noor Hassan',
    status: 'done',
    priority: 'high',
    dueDate: '2026-02-28',
    createdAt: '2026-02-01',
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-029',
    title: 'Checklist PDF pack',
    description: 'Distribute POS checklist PDF pack to stores.',
    projectId: 'prj-pos',
    projectName: 'Store POS Checklist',
    organizationId: 'org-summit',
    organizationName: 'Summit Retail Group',
    departmentId: 'dept-summit-exec',
    departmentName: 'Executive',
    assigneeId: 'usr-fahad',
    assigneeName: 'Fahad Mirza',
    assigneeInitials: 'FM',
    createdById: 'usr-fahad',
    createdByName: 'Fahad Mirza',
    status: 'done',
    priority: 'medium',
    dueDate: '2026-03-01',
    createdAt: '2026-01-20',
    subtasks: [],
    comments: [],
    attachments: [{ id: 'f1', name: 'pos-checklist.pdf', size: '420 KB' }],
  },
  {
    id: 'tsk-030',
    title: 'Merch alignment notes',
    description: 'Notes aligning merchandising with POS procedures.',
    projectId: 'prj-pos',
    projectName: 'Store POS Checklist',
    organizationId: 'org-summit',
    organizationName: 'Summit Retail Group',
    departmentId: 'dept-summit-mkt',
    departmentName: 'Marketing',
    assigneeId: 'usr-noor',
    assigneeName: 'Noor Hassan',
    assigneeInitials: 'NH',
    createdById: 'usr-fahad',
    createdByName: 'Fahad Mirza',
    status: 'done',
    priority: 'low',
    dueDate: '2026-03-15',
    createdAt: '2026-02-10',
    subtasks: [],
    comments: [],
    attachments: [],
  },

  // Canvas
  {
    id: 'tsk-031',
    title: 'Module peer review',
    description: 'Peer review Term 2 syllabus modules.',
    projectId: 'prj-syllabus',
    projectName: 'Term 2 Syllabus Pack',
    organizationId: 'org-canvas',
    organizationName: 'Canvas Education',
    departmentId: 'dept-canvas-exec',
    departmentName: 'Executive',
    assigneeId: 'usr-saima',
    assigneeName: 'Prof. Saima Riaz',
    assigneeInitials: 'SR',
    createdById: 'usr-saima',
    createdByName: 'Prof. Saima Riaz',
    status: 'in-review',
    priority: 'high',
    dueDate: '2026-07-30',
    createdAt: '2026-07-05',
    subtasks: [sub('s1', 'Assign reviewers', true), sub('s2', 'Collect notes', false)],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-032',
    title: 'Partner school outreach',
    description: 'Outreach sequence for partner school distribution.',
    projectId: 'prj-syllabus',
    projectName: 'Term 2 Syllabus Pack',
    organizationId: 'org-canvas',
    organizationName: 'Canvas Education',
    departmentId: 'dept-canvas-support',
    departmentName: 'Support',
    assigneeId: 'usr-haris',
    assigneeName: 'Haris Naveed',
    assigneeInitials: 'HN',
    createdById: 'usr-saima',
    createdByName: 'Prof. Saima Riaz',
    status: 'in-progress',
    priority: 'medium',
    dueDate: '2026-08-10',
    createdAt: '2026-07-08',
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-033',
    title: 'Draft onboarding agenda',
    description: 'Kickoff agenda for new district workshops.',
    projectId: 'prj-partner-districts',
    projectName: 'Partner Districts Onboarding',
    organizationId: 'org-canvas',
    organizationName: 'Canvas Education',
    departmentId: 'dept-canvas-support',
    departmentName: 'Support',
    assigneeId: 'usr-haris',
    assigneeName: 'Haris Naveed',
    assigneeInitials: 'HN',
    createdById: 'usr-haris',
    createdByName: 'Haris Naveed',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-08-20',
    createdAt: '2026-07-12',
    subtasks: [sub('s1', 'Outline'), sub('s2', 'Share for review')],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-034',
    title: 'Approve success metrics',
    description: 'Define success metrics for district onboarding.',
    projectId: 'prj-partner-districts',
    projectName: 'Partner Districts Onboarding',
    organizationId: 'org-canvas',
    organizationName: 'Canvas Education',
    departmentId: 'dept-canvas-exec',
    departmentName: 'Executive',
    assigneeId: 'usr-saima',
    assigneeName: 'Prof. Saima Riaz',
    assigneeInitials: 'SR',
    createdById: 'usr-haris',
    createdByName: 'Haris Naveed',
    status: 'todo',
    priority: 'low',
    dueDate: '2026-08-25',
    createdAt: '2026-07-14',
    subtasks: [],
    comments: [],
    attachments: [],
  },
  {
    id: 'tsk-035',
    title: 'Command palette empty state polish',
    description: 'Polish empty search illustration and clear CTA.',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    departmentId: 'dept-nova-design',
    departmentName: 'Design',
    assigneeId: 'usr-ahsan',
    assigneeName: 'Ahsan Taqweem',
    assigneeInitials: 'AT',
    createdById: 'usr-lina',
    createdByName: 'Lina Noor',
    status: 'todo',
    priority: 'low',
    dueDate: '2026-07-25',
    createdAt: '2026-07-23',
    subtasks: [],
    comments: [
      comment('c1', 'usr-lina', 'Lina Noor', 'LN', 'Can ship after Tasks module.', '1d ago'),
    ],
    attachments: [],
  },
];

export function getTaskById(id) {
  return TASKS.find((t) => t.id === id) || null;
}

export function getTasksByProject(projectId) {
  return TASKS.filter((t) => t.projectId === projectId);
}

export function getTasksByAssignee(assigneeId) {
  return TASKS.filter((t) => t.assigneeId === assigneeId);
}

export function filterTasks(
  list,
  {
    query = '',
    projectId = 'all',
    assigneeId = 'all',
    status = 'all',
    priority = 'all',
    myTasksOnly = false,
    dueBefore = '',
    dueAfter = '',
  } = {}
) {
  const q = query.trim().toLowerCase();
  return list.filter((t) => {
    if (myTasksOnly && t.assigneeId !== CURRENT_USER_ID) return false;
    if (projectId !== 'all' && t.projectId !== projectId) return false;
    if (assigneeId !== 'all' && t.assigneeId !== assigneeId) return false;
    if (status !== 'all' && t.status !== status) return false;
    if (priority !== 'all' && t.priority !== priority) return false;
    if (dueAfter && t.dueDate < dueAfter) return false;
    if (dueBefore && t.dueDate > dueBefore) return false;
    if (!q) return true;
    const hay = [t.title, t.projectName, t.assigneeName, t.description]
      .join(' ')
      .toLowerCase();
    return hay.includes(q);
  });
}

export function formatTaskDate(iso) {
  try {
    return new Date(iso).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  } catch {
    return iso;
  }
}

export function isOverdue(iso, status) {
  if (!iso || status === 'done') return false;
  try {
    const due = new Date(iso);
    const now = new Date('2026-07-26');
    return due < now;
  } catch {
    return false;
  }
}

export function groupTasksByStatus(list) {
  return TASK_STATUSES.map((status) => ({
    status,
    meta: TASK_STATUS_META[status],
    items: list.filter((t) => t.status === status),
  }));
}

export function projectTaskStats(projectId) {
  const items = getTasksByProject(projectId);
  const done = items.filter((t) => t.status === 'done').length;
  return { total: items.length, done };
}
