/**
 * Source of truth for Files & Folders.
 * Linked to users, projects, and tasks from existing catalogs.
 */

export const FILE_TYPES = ['doc', 'image', 'spreadsheet', 'pdf', 'code', 'other'];

export const FILE_TYPE_META = {
  doc: { label: 'Document', tone: 'text-sky-700 bg-sky-50 ring-sky-500/15' },
  image: { label: 'Image', tone: 'text-violet-700 bg-violet-50 ring-violet-500/15' },
  spreadsheet: { label: 'Spreadsheet', tone: 'text-emerald-700 bg-emerald-50 ring-emerald-500/15' },
  pdf: { label: 'PDF', tone: 'text-rose-700 bg-rose-50 ring-rose-500/15' },
  code: { label: 'Code', tone: 'text-amber-700 bg-amber-50 ring-amber-500/15' },
  other: { label: 'Other', tone: 'text-slate-600 bg-slate-100 ring-slate-300/50' },
};

export const STORAGE = { usedGb: 7.2, totalGb: 10 };

function version(id, label, userId, userName, time) {
  return { id, label, userId, userName, time };
}

function comment(id, userId, userName, initials, text, time) {
  return { id, userId, userName, initials, text, time };
}

export const FOLDERS = [
  {
    id: 'fld-root-product',
    name: 'Product',
    parentId: null,
    createdAt: '2026-03-12',
    createdById: 'usr-sara',
    createdByName: 'Sara Khan',
  },
  {
    id: 'fld-root-design',
    name: 'Design',
    parentId: null,
    createdAt: '2026-03-18',
    createdById: 'usr-lina',
    createdByName: 'Lina Noor',
  },
  {
    id: 'fld-root-eng',
    name: 'Engineering',
    parentId: null,
    createdAt: '2026-04-02',
    createdById: 'usr-raza',
    createdByName: 'M. Raza',
  },
  {
    id: 'fld-root-ops',
    name: 'Operations',
    parentId: null,
    createdAt: '2026-05-01',
    createdById: 'usr-bilal',
    createdByName: 'Bilal Ahmed',
  },
  {
    id: 'fld-product-specs',
    name: 'Specs',
    parentId: 'fld-root-product',
    createdAt: '2026-04-10',
    createdById: 'usr-sara',
    createdByName: 'Sara Khan',
  },
  {
    id: 'fld-design-assets',
    name: 'Assets',
    parentId: 'fld-root-design',
    createdAt: '2026-05-14',
    createdById: 'usr-lina',
    createdByName: 'Lina Noor',
  },
  {
    id: 'fld-eng-api',
    name: 'API Gateway',
    parentId: 'fld-root-eng',
    createdAt: '2026-06-01',
    createdById: 'usr-omar',
    createdByName: 'Omar Farooq',
  },
  {
    id: 'fld-eng-acb',
    name: 'ACB Core',
    parentId: 'fld-root-eng',
    createdAt: '2026-06-08',
    createdById: 'usr-ahsan',
    createdByName: 'Ahsan Taqweem',
  },
];

export const FILES = [
  {
    id: 'file-001',
    name: 'board-spec.pdf',
    type: 'pdf',
    mimeLabel: 'PDF Document',
    sizeBytes: 245760,
    sizeLabel: '240 KB',
    folderId: 'fld-product-specs',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    taskId: 'tsk-001',
    taskTitle: 'Build Projects list & board views',
    uploadedById: 'usr-raza',
    uploadedByName: 'M. Raza',
    uploadedByInitials: 'MR',
    uploadedAt: '2026-07-10',
    modifiedAt: '2026-07-18',
    versions: [
      version('v1', 'v1', 'usr-raza', 'M. Raza', '3 weeks ago'),
      version('v2', 'v2', 'usr-sara', 'Sara Khan', '1 week ago'),
      version('v3', 'v3', 'usr-raza', 'M. Raza', '2 days ago'),
    ],
    comments: [
      comment('c1', 'usr-sara', 'Sara Khan', 'SK', 'Looks good for sprint review.', '1d ago'),
    ],
  },
  {
    id: 'file-002',
    name: 'header.fig',
    type: 'other',
    mimeLabel: 'Figma Export',
    sizeBytes: 1258291,
    sizeLabel: '1.2 MB',
    folderId: 'fld-design-assets',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    taskId: 'tsk-003',
    taskTitle: 'Design project workspace header',
    uploadedById: 'usr-lina',
    uploadedByName: 'Lina Noor',
    uploadedByInitials: 'LN',
    uploadedAt: '2026-07-08',
    modifiedAt: '2026-07-15',
    versions: [version('v1', 'v1', 'usr-lina', 'Lina Noor', '2 weeks ago')],
    comments: [],
  },
  {
    id: 'file-003',
    name: 'limiter-rfc.md',
    type: 'doc',
    mimeLabel: 'Markdown',
    sizeBytes: 18432,
    sizeLabel: '18 KB',
    folderId: 'fld-eng-api',
    projectId: 'prj-api-gw',
    projectName: 'API Gateway v2',
    taskId: 'tsk-007',
    taskTitle: 'Implement token bucket limiter',
    uploadedById: 'usr-omar',
    uploadedByName: 'Omar Farooq',
    uploadedByInitials: 'OF',
    uploadedAt: '2026-07-05',
    modifiedAt: '2026-07-20',
    versions: [
      version('v1', 'v1', 'usr-omar', 'Omar Farooq', '3 weeks ago'),
      version('v2', 'v2', 'usr-raza', 'M. Raza', '6 days ago'),
    ],
    comments: [
      comment('c1', 'usr-raza', 'M. Raza', 'MR', 'Add burst capacity section.', '5d ago'),
    ],
  },
  {
    id: 'file-004',
    name: 'hipaa-checklist.xlsx',
    type: 'spreadsheet',
    mimeLabel: 'Excel Spreadsheet',
    sizeBytes: 88064,
    sizeLabel: '86 KB',
    folderId: 'fld-root-ops',
    projectId: 'prj-patient-intake',
    projectName: 'Patient Intake Digitization',
    taskId: 'tsk-021',
    taskTitle: 'HIPAA readiness checklist',
    uploadedById: 'usr-kamran',
    uploadedByName: 'Kamran Shah',
    uploadedByInitials: 'KS',
    uploadedAt: '2026-07-12',
    modifiedAt: '2026-07-12',
    versions: [version('v1', 'v1', 'usr-kamran', 'Kamran Shah', '2 weeks ago')],
    comments: [],
  },
  {
    id: 'file-005',
    name: 'pos-checklist.pdf',
    type: 'pdf',
    mimeLabel: 'PDF Document',
    sizeBytes: 430080,
    sizeLabel: '420 KB',
    folderId: 'fld-root-ops',
    projectId: 'prj-pos',
    projectName: 'Store POS Checklist',
    taskId: 'tsk-029',
    taskTitle: 'POS open/close checklist',
    uploadedById: 'usr-noor',
    uploadedByName: 'Noor Hassan',
    uploadedByInitials: 'NH',
    uploadedAt: '2026-07-14',
    modifiedAt: '2026-07-22',
    versions: [
      version('v1', 'v1', 'usr-noor', 'Noor Hassan', '12 days ago'),
      version('v2', 'v2', 'usr-fahad', 'Fahad Mirza', '4 days ago'),
    ],
    comments: [],
  },
  {
    id: 'file-006',
    name: 'token-palette.png',
    type: 'image',
    mimeLabel: 'PNG Image',
    sizeBytes: 512000,
    sizeLabel: '500 KB',
    folderId: 'fld-design-assets',
    projectId: 'prj-design-sys',
    projectName: 'Design System 2.0',
    taskId: 'tsk-010',
    taskTitle: 'Document color tokens',
    uploadedById: 'usr-lina',
    uploadedByName: 'Lina Noor',
    uploadedByInitials: 'LN',
    uploadedAt: '2026-07-11',
    modifiedAt: '2026-07-11',
    versions: [version('v1', 'v1', 'usr-lina', 'Lina Noor', '2 weeks ago')],
    comments: [
      comment('c1', 'usr-ahsan', 'Ahsan Taqweem', 'AT', 'Ship these into Tailwind theme.', '1w ago'),
    ],
  },
  {
    id: 'file-007',
    name: 'spring-presets.ts',
    type: 'code',
    mimeLabel: 'TypeScript',
    sizeBytes: 6144,
    sizeLabel: '6 KB',
    folderId: 'fld-eng-acb',
    projectId: 'prj-design-sys',
    projectName: 'Design System 2.0',
    taskId: 'tsk-011',
    taskTitle: 'Motion spring presets',
    uploadedById: 'usr-lina',
    uploadedByName: 'Lina Noor',
    uploadedByInitials: 'LN',
    uploadedAt: '2026-07-16',
    modifiedAt: '2026-07-19',
    versions: [version('v1', 'v1', 'usr-lina', 'Lina Noor', '10 days ago')],
    comments: [],
  },
  {
    id: 'file-008',
    name: 'security-checklist.docx',
    type: 'doc',
    mimeLabel: 'Word Document',
    sizeBytes: 97280,
    sizeLabel: '95 KB',
    folderId: 'fld-eng-acb',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    taskId: 'tsk-005',
    taskTitle: 'Security checklist for project files tab',
    uploadedById: 'usr-ahsan',
    uploadedByName: 'Ahsan Taqweem',
    uploadedByInitials: 'AT',
    uploadedAt: '2026-07-20',
    modifiedAt: '2026-07-25',
    versions: [
      version('v1', 'v1', 'usr-ahsan', 'Ahsan Taqweem', '6 days ago'),
      version('v2', 'v2', 'usr-ahsan', 'Ahsan Taqweem', '1 day ago'),
    ],
    comments: [
      comment('c1', 'usr-raza', 'M. Raza', 'MR', 'Add attachment ACL section.', '12h ago'),
    ],
  },
  {
    id: 'file-009',
    name: 'onboarding-emails.docx',
    type: 'doc',
    mimeLabel: 'Word Document',
    sizeBytes: 153600,
    sizeLabel: '150 KB',
    folderId: 'fld-root-product',
    projectId: 'prj-onboarding',
    projectName: 'People Ops Onboarding',
    taskId: 'tsk-013',
    taskTitle: 'Welcome email templates',
    uploadedById: 'usr-hira',
    uploadedByName: 'Hira Ali',
    uploadedByInitials: 'HA',
    uploadedAt: '2026-07-09',
    modifiedAt: '2026-07-17',
    versions: [version('v1', 'v1', 'usr-hira', 'Hira Ali', '2 weeks ago')],
    comments: [],
  },
  {
    id: 'file-010',
    name: 'cold-chain-alerts.csv',
    type: 'spreadsheet',
    mimeLabel: 'CSV',
    sizeBytes: 40960,
    sizeLabel: '40 KB',
    folderId: 'fld-root-ops',
    projectId: 'prj-cold-chain',
    projectName: 'Cold Chain Hub',
    taskId: 'tsk-015',
    taskTitle: 'Alert thresholds for freezers',
    uploadedById: 'usr-bilal',
    uploadedByName: 'Bilal Ahmed',
    uploadedByInitials: 'BA',
    uploadedAt: '2026-07-13',
    modifiedAt: '2026-07-21',
    versions: [version('v1', 'v1', 'usr-bilal', 'Bilal Ahmed', '13 days ago')],
    comments: [],
  },
  {
    id: 'file-011',
    name: 'hub-photo-north.jpg',
    type: 'image',
    mimeLabel: 'JPEG Image',
    sizeBytes: 2100000,
    sizeLabel: '2.0 MB',
    folderId: 'fld-root-ops',
    projectId: 'prj-harbor-exp',
    projectName: 'Regional Expansion Map',
    taskId: null,
    taskTitle: null,
    uploadedById: 'usr-usman',
    uploadedByName: 'Usman Tariq',
    uploadedByInitials: 'UT',
    uploadedAt: '2026-07-07',
    modifiedAt: '2026-07-07',
    versions: [version('v1', 'v1', 'usr-usman', 'Usman Tariq', '19 days ago')],
    comments: [],
  },
  {
    id: 'file-012',
    name: 'otel-dashboard.json',
    type: 'code',
    mimeLabel: 'JSON',
    sizeBytes: 28672,
    sizeLabel: '28 KB',
    folderId: 'fld-eng-api',
    projectId: 'prj-api-gw',
    projectName: 'API Gateway v2',
    taskId: 'tsk-008',
    taskTitle: 'Add OpenTelemetry traces',
    uploadedById: 'usr-raza',
    uploadedByName: 'M. Raza',
    uploadedByInitials: 'MR',
    uploadedAt: '2026-07-15',
    modifiedAt: '2026-07-23',
    versions: [version('v1', 'v1', 'usr-raza', 'M. Raza', '11 days ago')],
    comments: [],
  },
  {
    id: 'file-013',
    name: 'q2-control-matrix.xlsx',
    type: 'spreadsheet',
    mimeLabel: 'Excel Spreadsheet',
    sizeBytes: 220160,
    sizeLabel: '215 KB',
    folderId: null,
    projectId: 'prj-q2-audit',
    projectName: 'Q2 Compliance Audit',
    taskId: 'tsk-024',
    taskTitle: 'Gather bank reconciliations',
    uploadedById: 'usr-mehwish',
    uploadedByName: 'Mehwish Rauf',
    uploadedByInitials: 'MR',
    uploadedAt: '2026-07-06',
    modifiedAt: '2026-07-24',
    versions: [
      version('v1', 'v1', 'usr-mehwish', 'Mehwish Rauf', '3 weeks ago'),
      version('v2', 'v2', 'usr-imran', 'Imran Qureshi', '2 days ago'),
    ],
    comments: [
      comment('c1', 'usr-imran', 'Imran Qureshi', 'IQ', 'Controls 12–18 updated.', '2d ago'),
    ],
  },
  {
    id: 'file-014',
    name: 'ramadan-moodboard.png',
    type: 'image',
    mimeLabel: 'PNG Image',
    sizeBytes: 1800000,
    sizeLabel: '1.7 MB',
    folderId: 'fld-root-design',
    projectId: 'prj-ramadan',
    projectName: 'Ramadan Campaign Board',
    taskId: null,
    taskTitle: null,
    uploadedById: 'usr-fahad',
    uploadedByName: 'Fahad Mirza',
    uploadedByInitials: 'FM',
    uploadedAt: '2026-07-18',
    modifiedAt: '2026-07-18',
    versions: [version('v1', 'v1', 'usr-fahad', 'Fahad Mirza', '8 days ago')],
    comments: [],
  },
  {
    id: 'file-015',
    name: 'partner-playbook.pdf',
    type: 'pdf',
    mimeLabel: 'PDF Document',
    sizeBytes: 890880,
    sizeLabel: '870 KB',
    folderId: 'fld-root-product',
    projectId: 'prj-partner-districts',
    projectName: 'Partner Districts Onboarding',
    taskId: 'tsk-033',
    taskTitle: 'Draft onboarding agenda',
    uploadedById: 'usr-haris',
    uploadedByName: 'Haris Naveed',
    uploadedByInitials: 'HN',
    uploadedAt: '2026-07-19',
    modifiedAt: '2026-07-26',
    versions: [version('v1', 'v1', 'usr-haris', 'Haris Naveed', '1 week ago')],
    comments: [],
  },
  {
    id: 'file-016',
    name: 'syllabus-term2.pdf',
    type: 'pdf',
    mimeLabel: 'PDF Document',
    sizeBytes: 1507328,
    sizeLabel: '1.4 MB',
    folderId: null,
    projectId: 'prj-syllabus',
    projectName: 'Term 2 Syllabus Pack',
    taskId: null,
    taskTitle: null,
    uploadedById: 'usr-saima',
    uploadedByName: 'Prof. Saima Riaz',
    uploadedByInitials: 'SR',
    uploadedAt: '2026-07-04',
    modifiedAt: '2026-07-16',
    versions: [version('v1', 'v1', 'usr-saima', 'Prof. Saima Riaz', '3 weeks ago')],
    comments: [],
  },
  {
    id: 'file-017',
    name: 'mfa-rollout-plan.docx',
    type: 'doc',
    mimeLabel: 'Word Document',
    sizeBytes: 112640,
    sizeLabel: '110 KB',
    folderId: 'fld-root-eng',
    projectId: 'prj-mfa-rollout',
    projectName: 'Clinic MFA Rollout',
    taskId: 'tsk-022',
    taskTitle: 'Admin MFA policy',
    uploadedById: 'usr-kamran',
    uploadedByName: 'Kamran Shah',
    uploadedByInitials: 'KS',
    uploadedAt: '2026-07-21',
    modifiedAt: '2026-07-21',
    versions: [version('v1', 'v1', 'usr-kamran', 'Kamran Shah', '5 days ago')],
    comments: [],
  },
  {
    id: 'file-018',
    name: 'tenant-routing.md',
    type: 'doc',
    mimeLabel: 'Markdown',
    sizeBytes: 22528,
    sizeLabel: '22 KB',
    folderId: 'fld-eng-api',
    projectId: 'prj-api-gw',
    projectName: 'API Gateway v2',
    taskId: 'tsk-009',
    taskTitle: 'Document tenant routing',
    uploadedById: 'usr-raza',
    uploadedByName: 'M. Raza',
    uploadedByInitials: 'MR',
    uploadedAt: '2026-07-17',
    modifiedAt: '2026-07-22',
    versions: [version('v1', 'v1', 'usr-raza', 'M. Raza', '9 days ago')],
    comments: [],
  },
  {
    id: 'file-019',
    name: 'product-roadmap.pdf',
    type: 'pdf',
    mimeLabel: 'PDF Document',
    sizeBytes: 655360,
    sizeLabel: '640 KB',
    folderId: 'fld-root-product',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    taskId: null,
    taskTitle: null,
    uploadedById: 'usr-sara',
    uploadedByName: 'Sara Khan',
    uploadedByInitials: 'SK',
    uploadedAt: '2026-06-28',
    modifiedAt: '2026-07-14',
    versions: [
      version('v1', 'v1', 'usr-sara', 'Sara Khan', '1 month ago'),
      version('v2', 'v2', 'usr-sara', 'Sara Khan', '12 days ago'),
    ],
    comments: [],
  },
  {
    id: 'file-020',
    name: 'empty-state-mock.png',
    type: 'image',
    mimeLabel: 'PNG Image',
    sizeBytes: 340000,
    sizeLabel: '332 KB',
    folderId: 'fld-design-assets',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    taskId: 'tsk-035',
    taskTitle: 'Command palette empty state polish',
    uploadedById: 'usr-ahsan',
    uploadedByName: 'Ahsan Taqweem',
    uploadedByInitials: 'AT',
    uploadedAt: '2026-07-23',
    modifiedAt: '2026-07-23',
    versions: [version('v1', 'v1', 'usr-ahsan', 'Ahsan Taqweem', '3 days ago')],
    comments: [],
  },
  {
    id: 'file-021',
    name: 'tasks-module-brief.docx',
    type: 'doc',
    mimeLabel: 'Word Document',
    sizeBytes: 73728,
    sizeLabel: '72 KB',
    folderId: 'fld-product-specs',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    taskId: 'tsk-006',
    taskTitle: 'Promote tasks into standalone module',
    uploadedById: 'usr-sara',
    uploadedByName: 'Sara Khan',
    uploadedByInitials: 'SK',
    uploadedAt: '2026-07-02',
    modifiedAt: '2026-07-12',
    versions: [version('v1', 'v1', 'usr-sara', 'Sara Khan', '3 weeks ago')],
    comments: [],
  },
  {
    id: 'file-022',
    name: 'fleet-rules.xlsx',
    type: 'spreadsheet',
    mimeLabel: 'Excel Spreadsheet',
    sizeBytes: 55296,
    sizeLabel: '54 KB',
    folderId: 'fld-root-ops',
    projectId: 'prj-cold-chain',
    projectName: 'Cold Chain Hub',
    taskId: 'tsk-016',
    taskTitle: 'Fleet assignment rules',
    uploadedById: 'usr-usman',
    uploadedByName: 'Usman Tariq',
    uploadedByInitials: 'UT',
    uploadedAt: '2026-07-25',
    modifiedAt: '2026-07-25',
    versions: [version('v1', 'v1', 'usr-usman', 'Usman Tariq', '1 day ago')],
    comments: [],
  },
  {
    id: 'file-023',
    name: 'vite.config.snippet.js',
    type: 'code',
    mimeLabel: 'JavaScript',
    sizeBytes: 4096,
    sizeLabel: '4 KB',
    folderId: 'fld-eng-acb',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    taskId: null,
    taskTitle: null,
    uploadedById: 'usr-omar',
    uploadedByName: 'Omar Farooq',
    uploadedByInitials: 'OF',
    uploadedAt: '2026-07-24',
    modifiedAt: '2026-07-24',
    versions: [version('v1', 'v1', 'usr-omar', 'Omar Farooq', '2 days ago')],
    comments: [],
  },
  {
    id: 'file-024',
    name: 'intake-wireframes.pdf',
    type: 'pdf',
    mimeLabel: 'PDF Document',
    sizeBytes: 1024000,
    sizeLabel: '1.0 MB',
    folderId: 'fld-root-design',
    projectId: 'prj-patient-intake',
    projectName: 'Patient Intake Digitization',
    taskId: 'tsk-020',
    taskTitle: 'Digitize intake forms',
    uploadedById: 'usr-amna',
    uploadedByName: 'Dr. Amna Siddiqui',
    uploadedByInitials: 'AS',
    uploadedAt: '2026-07-08',
    modifiedAt: '2026-07-15',
    versions: [version('v1', 'v1', 'usr-amna', 'Dr. Amna Siddiqui', '18 days ago')],
    comments: [],
  },
  {
    id: 'file-025',
    name: 'brand-guidelines.pdf',
    type: 'pdf',
    mimeLabel: 'PDF Document',
    sizeBytes: 2800000,
    sizeLabel: '2.7 MB',
    folderId: 'fld-root-design',
    projectId: null,
    projectName: null,
    taskId: null,
    taskTitle: null,
    uploadedById: 'usr-ayesha',
    uploadedByName: 'Ayesha Bukhari',
    uploadedByInitials: 'AB',
    uploadedAt: '2026-07-01',
    modifiedAt: '2026-07-01',
    versions: [version('v1', 'v1', 'usr-ayesha', 'Ayesha Bukhari', '25 days ago')],
    comments: [],
  },
  {
    id: 'file-026',
    name: 'weekly-standup-notes.docx',
    type: 'doc',
    mimeLabel: 'Word Document',
    sizeBytes: 32768,
    sizeLabel: '32 KB',
    folderId: null,
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    taskId: null,
    taskTitle: null,
    uploadedById: 'usr-ahsan',
    uploadedByName: 'Ahsan Taqweem',
    uploadedByInitials: 'AT',
    uploadedAt: '2026-07-26',
    modifiedAt: '2026-07-26',
    versions: [version('v1', 'v1', 'usr-ahsan', 'Ahsan Taqweem', 'Today')],
    comments: [],
  },
  {
    id: 'file-027',
    name: 'archive.zip',
    type: 'other',
    mimeLabel: 'ZIP Archive',
    sizeBytes: 4500000,
    sizeLabel: '4.3 MB',
    folderId: 'fld-root-eng',
    projectId: null,
    projectName: null,
    taskId: null,
    taskTitle: null,
    uploadedById: 'usr-omar',
    uploadedByName: 'Omar Farooq',
    uploadedByInitials: 'OF',
    uploadedAt: '2026-06-20',
    modifiedAt: '2026-06-20',
    versions: [version('v1', 'v1', 'usr-omar', 'Omar Farooq', '5 weeks ago')],
    comments: [],
  },
  {
    id: 'file-028',
    name: 'site-criteria.xlsx',
    type: 'spreadsheet',
    mimeLabel: 'Excel Spreadsheet',
    sizeBytes: 67584,
    sizeLabel: '66 KB',
    folderId: 'fld-root-ops',
    projectId: 'prj-harbor-exp',
    projectName: 'Regional Expansion Map',
    taskId: 'tsk-018',
    taskTitle: 'Compile site criteria',
    uploadedById: 'usr-nadia',
    uploadedByName: 'Nadia Rehman',
    uploadedByInitials: 'NR',
    uploadedAt: '2026-07-22',
    modifiedAt: '2026-07-22',
    versions: [version('v1', 'v1', 'usr-nadia', 'Nadia Rehman', '4 days ago')],
    comments: [],
  },
  {
    id: 'file-029',
    name: 'logo-mark.svg',
    type: 'image',
    mimeLabel: 'SVG Image',
    sizeBytes: 8192,
    sizeLabel: '8 KB',
    folderId: 'fld-design-assets',
    projectId: 'prj-design-sys',
    projectName: 'Design System 2.0',
    taskId: null,
    taskTitle: null,
    uploadedById: 'usr-lina',
    uploadedByName: 'Lina Noor',
    uploadedByInitials: 'LN',
    uploadedAt: '2026-07-03',
    modifiedAt: '2026-07-03',
    versions: [version('v1', 'v1', 'usr-lina', 'Lina Noor', '23 days ago')],
    comments: [],
  },
  {
    id: 'file-030',
    name: 'release-notes-q2.md',
    type: 'doc',
    mimeLabel: 'Markdown',
    sizeBytes: 14336,
    sizeLabel: '14 KB',
    folderId: 'fld-root-product',
    projectId: 'prj-acb-core',
    projectName: 'AI Company Brain Core',
    taskId: null,
    taskTitle: null,
    uploadedById: 'usr-sara',
    uploadedByName: 'Sara Khan',
    uploadedByInitials: 'SK',
    uploadedAt: '2026-07-25',
    modifiedAt: '2026-07-26',
    versions: [version('v1', 'v1', 'usr-sara', 'Sara Khan', '1 day ago')],
    comments: [
      comment('c1', 'usr-ahsan', 'Ahsan Taqweem', 'AT', 'Mention Meetings + Time Tracking.', '8h ago'),
    ],
  },
];

export function getFolderById(id) {
  return FOLDERS.find((f) => f.id === id) || null;
}

export function getFileById(id) {
  return FILES.find((f) => f.id === id) || null;
}

export function getChildFolders(parentId) {
  return FOLDERS.filter((f) => f.parentId === parentId);
}

export function getFilesInFolder(folderId) {
  return FILES.filter((f) => f.folderId === folderId);
}

export function getFilesByProject(projectId) {
  return FILES.filter((f) => f.projectId === projectId);
}

export function getFilesByTask(taskId) {
  return FILES.filter((f) => f.taskId === taskId);
}

export function getFilesByUploader(userId) {
  return FILES.filter((f) => f.uploadedById === userId);
}

export function getBreadcrumb(folderId) {
  const trail = [];
  let current = folderId ? getFolderById(folderId) : null;
  while (current) {
    trail.unshift(current);
    current = current.parentId ? getFolderById(current.parentId) : null;
  }
  return trail;
}

export function formatFileDate(iso) {
  try {
    return new Date(`${iso}T12:00:00`).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  } catch {
    return iso;
  }
}

export function filterAndSortFiles(
  files,
  { query = '', type = 'all', projectId = 'all', sort = 'name' } = {}
) {
  const q = query.trim().toLowerCase();
  let list = files.filter((f) => {
    if (type !== 'all' && f.type !== type) return false;
    if (projectId !== 'all' && f.projectId !== projectId) return false;
    if (!q) return true;
    return [f.name, f.projectName, f.uploadedByName, f.taskTitle]
      .filter(Boolean)
      .join(' ')
      .toLowerCase()
      .includes(q);
  });

  list = [...list].sort((a, b) => {
    if (sort === 'date') return b.uploadedAt.localeCompare(a.uploadedAt);
    if (sort === 'size') return (b.sizeBytes || 0) - (a.sizeBytes || 0);
    return a.name.localeCompare(b.name);
  });
  return list;
}

export function filterFolders(folders, query = '') {
  const q = query.trim().toLowerCase();
  if (!q) return folders;
  return folders.filter((f) => f.name.toLowerCase().includes(q));
}
