/**
 * Static departments — linked to organizationData.js + userData.js IDs.
 */
export const DEPARTMENTS = [
  {
    id: 'dept-nova-eng',
    name: 'Engineering',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    managerId: 'usr-raza',
    managerName: 'M. Raza',
    managerInitials: 'MR',
    memberIds: ['usr-raza', 'usr-omar'],
    projectCount: 12,
    status: 'active',
    createdAt: '2024-03-20',
    avgTenureMonths: 14,
    description:
      'Platform, infrastructure, and product engineering for AI Company Brain and client deliveries.',
    iconTone: 'from-[#EFF6FF] to-[#BFDBFE] text-primary',
    accent: 'bg-primary',
  },
  {
    id: 'dept-nova-product',
    name: 'Product',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    managerId: 'usr-sara',
    managerName: 'Sara Khan',
    managerInitials: 'SK',
    memberIds: ['usr-sara', 'usr-guest'],
    projectCount: 8,
    status: 'active',
    createdAt: '2024-04-05',
    avgTenureMonths: 11,
    description: 'Roadmaps, discovery, and product operations across SaaS workspaces.',
    iconTone: 'from-[#F5F3FF] to-[#DDD6FE] text-violet-600',
    accent: 'bg-violet-500',
  },
  {
    id: 'dept-nova-design',
    name: 'Design',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    managerId: 'usr-lina',
    managerName: 'Lina Noor',
    managerInitials: 'LN',
    memberIds: ['usr-lina'],
    projectCount: 6,
    status: 'active',
    createdAt: '2024-06-22',
    avgTenureMonths: 9,
    description: 'Design systems, UX research, and premium interface craft.',
    iconTone: 'from-[#FDF2F8] to-[#FBCFE8] text-pink-600',
    accent: 'bg-pink-500',
  },
  {
    id: 'dept-nova-hr',
    name: 'HR',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    managerId: 'usr-hira',
    managerName: 'Hira Ali',
    managerInitials: 'HA',
    memberIds: ['usr-hira'],
    projectCount: 3,
    status: 'active',
    createdAt: '2024-08-01',
    avgTenureMonths: 10,
    description: 'People ops, onboarding, and employee success programs.',
    iconTone: 'from-[#ECFDF5] to-[#A7F3D0] text-emerald-600',
    accent: 'bg-emerald-500',
  },
  {
    id: 'dept-nova-exec',
    name: 'Executive',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    managerId: 'usr-ahsan',
    managerName: 'Ahsan Taqweem',
    managerInitials: 'AT',
    memberIds: ['usr-ahsan'],
    projectCount: 4,
    status: 'active',
    createdAt: '2024-03-12',
    avgTenureMonths: 16,
    description: 'Leadership, strategy, and cross-organization governance.',
    iconTone: 'from-[#FFF7ED] to-[#FED7AA] text-orange-600',
    accent: 'bg-orange-500',
  },
  {
    id: 'dept-harbor-ops',
    name: 'Operations',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Logistics',
    managerId: 'usr-bilal',
    managerName: 'Bilal Ahmed',
    managerInitials: 'BA',
    memberIds: ['usr-bilal', 'usr-usman'],
    projectCount: 15,
    status: 'active',
    createdAt: '2023-11-10',
    avgTenureMonths: 22,
    description: 'Hub operations, fleet coordination, and warehouse digital workflows.',
    iconTone: 'from-[#ECFEFF] to-[#A5F3FC] text-cyan-700',
    accent: 'bg-cyan-600',
  },
  {
    id: 'dept-harbor-exec',
    name: 'Executive',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Logistics',
    managerId: 'usr-nadia',
    managerName: 'Nadia Rehman',
    managerInitials: 'NR',
    memberIds: ['usr-nadia'],
    projectCount: 5,
    status: 'active',
    createdAt: '2023-11-02',
    avgTenureMonths: 28,
    description: 'Executive oversight for regional logistics expansion.',
    iconTone: 'from-[#EFF6FF] to-[#BFDBFE] text-primary',
    accent: 'bg-primary',
  },
  {
    id: 'dept-pulse-clinical',
    name: 'Clinical',
    organizationId: 'org-pulse',
    organizationName: 'Pulse Health Group',
    managerId: 'usr-amna',
    managerName: 'Dr. Amna Siddiqui',
    managerInitials: 'AS',
    memberIds: ['usr-amna'],
    projectCount: 7,
    status: 'active',
    createdAt: '2024-07-18',
    avgTenureMonths: 12,
    description: 'Clinical operations, care pathways, and patient coordination.',
    iconTone: 'from-[#ECFDF5] to-[#A7F3D0] text-emerald-700',
    accent: 'bg-emerald-600',
  },
  {
    id: 'dept-pulse-it',
    name: 'IT',
    organizationId: 'org-pulse',
    organizationName: 'Pulse Health Group',
    managerId: 'usr-kamran',
    managerName: 'Kamran Shah',
    managerInitials: 'KS',
    memberIds: ['usr-kamran'],
    projectCount: 5,
    status: 'active',
    createdAt: '2024-07-25',
    avgTenureMonths: 11,
    description: 'Health IT systems, security controls, and clinic tooling.',
    iconTone: 'from-[#EEF2FF] to-[#C7D2FE] text-indigo-600',
    accent: 'bg-indigo-500',
  },
  {
    id: 'dept-ledger-finance',
    name: 'Finance',
    organizationId: 'org-ledger',
    organizationName: 'Ledger & Co.',
    managerId: 'usr-mehwish',
    managerName: 'Mehwish Rauf',
    managerInitials: 'MR',
    memberIds: ['usr-imran', 'usr-mehwish', 'usr-zain'],
    projectCount: 6,
    status: 'active',
    createdAt: '2025-01-09',
    avgTenureMonths: 8,
    description: 'Advisory, compliance, and client financial reporting.',
    iconTone: 'from-[#FFFBEB] to-[#FDE68A] text-amber-700',
    accent: 'bg-amber-500',
  },
  {
    id: 'dept-summit-mkt',
    name: 'Marketing',
    organizationId: 'org-summit',
    organizationName: 'Summit Retail Group',
    managerId: 'usr-noor',
    managerName: 'Noor Hassan',
    managerInitials: 'NH',
    memberIds: ['usr-noor'],
    projectCount: 11,
    status: 'active',
    createdAt: '2023-01-15',
    avgTenureMonths: 30,
    description: 'Merchandising campaigns, brand systems, and retail growth.',
    iconTone: 'from-[#FEF2F2] to-[#FECACA] text-red-600',
    accent: 'bg-red-500',
  },
  {
    id: 'dept-canvas-support',
    name: 'Support',
    organizationId: 'org-canvas',
    organizationName: 'Canvas Education',
    managerId: 'usr-haris',
    managerName: 'Haris Naveed',
    managerInitials: 'HN',
    memberIds: ['usr-haris'],
    projectCount: 4,
    status: 'active',
    createdAt: '2024-11-12',
    avgTenureMonths: 7,
    description: 'Partner support, school onboarding, and success programs.',
    iconTone: 'from-[#F0FDF4] to-[#BBF7D0] text-green-700',
    accent: 'bg-green-600',
  },
  {
    id: 'dept-summit-exec',
    name: 'Executive',
    organizationId: 'org-summit',
    organizationName: 'Summit Retail Group',
    managerId: 'usr-fahad',
    managerName: 'Fahad Mirza',
    managerInitials: 'FM',
    memberIds: ['usr-fahad'],
    projectCount: 9,
    status: 'active',
    createdAt: '2022-09-14',
    avgTenureMonths: 40,
    description: 'Retail leadership, omnichannel strategy, and regional growth.',
    iconTone: 'from-[#FEF2F2] to-[#FECACA] text-red-700',
    accent: 'bg-red-600',
  },
  {
    id: 'dept-canvas-exec',
    name: 'Executive',
    organizationId: 'org-canvas',
    organizationName: 'Canvas Education',
    managerId: 'usr-saima',
    managerName: 'Prof. Saima Riaz',
    managerInitials: 'SR',
    memberIds: ['usr-saima'],
    projectCount: 5,
    status: 'active',
    createdAt: '2024-10-30',
    avgTenureMonths: 9,
    description: 'Academic leadership and partner school governance.',
    iconTone: 'from-[#EFF6FF] to-[#BFDBFE] text-primary',
    accent: 'bg-primary',
  },
  {
    id: 'dept-orbit-mkt',
    name: 'Marketing',
    organizationId: 'org-orbit',
    organizationName: 'Orbit Media Labs',
    managerId: 'usr-ayesha',
    managerName: 'Ayesha Bukhari',
    managerInitials: 'AB',
    memberIds: ['usr-ayesha'],
    projectCount: 2,
    status: 'inactive',
    createdAt: '2023-05-21',
    avgTenureMonths: 24,
    description: 'Creative studio archive — marketing retained for historical work.',
    iconTone: 'from-[#F5F3FF] to-[#DDD6FE] text-violet-700',
    accent: 'bg-violet-600',
  },
];

export function getDepartmentById(id) {
  return DEPARTMENTS.find((d) => d.id === id) || null;
}

export function getDepartmentsByOrganization(organizationId) {
  return DEPARTMENTS.filter((d) => d.organizationId === organizationId);
}

export function filterDepartments(
  list,
  { query = '', organizationId = 'all', managerId = 'all' } = {}
) {
  const q = query.trim().toLowerCase();
  return list.filter((dept) => {
    if (organizationId !== 'all' && dept.organizationId !== organizationId) return false;
    if (managerId !== 'all' && dept.managerId !== managerId) return false;
    if (!q) return true;
    const hay = [dept.name, dept.organizationName, dept.managerName, dept.description]
      .join(' ')
      .toLowerCase();
    return hay.includes(q);
  });
}

export function formatDeptDate(iso) {
  try {
    return new Date(iso).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  } catch {
    return iso;
  }
}

/** Managers eligible for create/filter selects (Dept Manager or higher) */
export const DEPARTMENT_MANAGER_OPTIONS = [
  { id: 'usr-ahsan', name: 'Ahsan Taqweem' },
  { id: 'usr-sara', name: 'Sara Khan' },
  { id: 'usr-raza', name: 'M. Raza' },
  { id: 'usr-lina', name: 'Lina Noor' },
  { id: 'usr-hira', name: 'Hira Ali' },
  { id: 'usr-nadia', name: 'Nadia Rehman' },
  { id: 'usr-bilal', name: 'Bilal Ahmed' },
  { id: 'usr-amna', name: 'Dr. Amna Siddiqui' },
  { id: 'usr-kamran', name: 'Kamran Shah' },
  { id: 'usr-mehwish', name: 'Mehwish Rauf' },
  { id: 'usr-imran', name: 'Imran Qureshi' },
  { id: 'usr-fahad', name: 'Fahad Mirza' },
  { id: 'usr-noor', name: 'Noor Hassan' },
  { id: 'usr-saima', name: 'Prof. Saima Riaz' },
  { id: 'usr-haris', name: 'Haris Naveed' },
];
