/**
 * Static users catalog — linked to organization IDs from organizationData.js
 */
import {
  LogIn,
  UserPlus,
  CheckCircle2,
  FolderKanban,
  Shield,
  Mail,
} from 'lucide-react';

export const USER_ROLES = [
  'Super Admin',
  'Org Owner',
  'Org Admin',
  'Dept Manager',
  'Team Lead',
  'Employee',
  'HR',
  'Guest',
];

export const USER_STATUSES = ['active', 'invited', 'suspended'];

export const DEPARTMENTS = [
  'Executive',
  'Engineering',
  'Product',
  'Design',
  'Operations',
  'Finance',
  'HR',
  'Clinical',
  'IT',
  'Marketing',
  'Support',
];

/** Role badge tones */
export const ROLE_META = {
  'Super Admin': { tone: 'bg-rose-50 text-rose-700 ring-rose-500/15' },
  'Org Owner': { tone: 'bg-primary/10 text-primary ring-primary/15' },
  'Org Admin': { tone: 'bg-violet-50 text-violet-700 ring-violet-500/15' },
  'Dept Manager': { tone: 'bg-amber-50 text-amber-700 ring-amber-500/15' },
  'Team Lead': { tone: 'bg-cyan-50 text-cyan-700 ring-cyan-500/15' },
  Employee: { tone: 'bg-slate-100 text-slate-600 ring-slate-300/50' },
  HR: { tone: 'bg-emerald-50 text-emerald-700 ring-emerald-500/15' },
  Guest: { tone: 'bg-orange-50 text-orange-700 ring-orange-500/15' },
};

export const STATUS_META = {
  active: {
    label: 'Active',
    tone: 'bg-emerald-50 text-emerald-700 ring-emerald-500/15',
    dot: 'bg-success',
  },
  invited: {
    label: 'Invited',
    tone: 'bg-blue-50 text-primary ring-primary/15',
    dot: 'bg-primary',
  },
  suspended: {
    label: 'Suspended',
    tone: 'bg-slate-100 text-slate-500 ring-slate-300/50',
    dot: 'bg-slate-400',
  },
};

const activityIcon = {
  login: LogIn,
  invite: UserPlus,
  task: CheckCircle2,
  project: FolderKanban,
  permission: Shield,
  email: Mail,
};

const activityColor = {
  login: 'bg-gradient-to-br from-primary to-[#1D4ED8]',
  invite: 'bg-gradient-to-br from-[#7C3AED] to-[#8B5CF6]',
  task: 'bg-gradient-to-br from-[#059669] to-[#10B981]',
  project: 'bg-gradient-to-br from-[#D97706] to-[#F59E0B]',
  permission: 'bg-gradient-to-br from-[#DC2626] to-[#EF4444]',
  email: 'bg-gradient-to-br from-[#0891B2] to-[#06B6D4]',
};

function act(type, title, detail, time) {
  return {
    type,
    title,
    detail,
    time,
    icon: activityIcon[type] || LogIn,
    color: activityColor[type] || activityColor.login,
  };
}

export const USERS = [
  {
    id: 'usr-ahsan',
    name: 'Ahsan Taqweem',
    email: 'ahsan@novatech.io',
    initials: 'AT',
    role: 'Super Admin',
    department: 'Executive',
    departmentId: 'dept-nova-exec',
    team: 'Platform Leadership',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    status: 'active',
    joinedAt: '2024-03-12',
    lastActive: '2m ago',
    lastLogin: 'Today, 9:14 AM',
    manager: null,
    phone: '+971 50 123 4567',
    location: 'Dubai, UAE',
    tasksAssigned: 12,
    projects: 8,
    activity: [
      act('login', 'Signed in', 'Chrome · Dubai', '2m ago'),
      act('permission', 'Updated roles', 'Granted Org Admin to Sara Khan', '1h ago'),
      act('project', 'Opened project', 'AI Company Brain workspace', '3h ago'),
      act('invite', 'Invited user', 'Omar Farooq · Engineering', 'Yesterday'),
    ],
  },
  {
    id: 'usr-sara',
    name: 'Sara Khan',
    email: 'sara@novatech.io',
    initials: 'SK',
    role: 'Org Admin',
    department: 'Product',
    departmentId: 'dept-nova-product',
    team: 'Product Ops',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    status: 'active',
    joinedAt: '2024-04-02',
    lastActive: '18m ago',
    lastLogin: 'Today, 8:40 AM',
    manager: 'Ahsan Taqweem',
    phone: '+971 55 222 1100',
    location: 'Dubai, UAE',
    tasksAssigned: 24,
    projects: 6,
    activity: [
      act('task', 'Completed task', 'Notifications UI polish', '18m ago'),
      act('invite', 'Invited members', '3 seats to Product', '2h ago'),
      act('login', 'Signed in', 'Safari · Dubai', '8:40 AM'),
    ],
  },
  {
    id: 'usr-raza',
    name: 'M. Raza',
    email: 'raza@novatech.io',
    initials: 'MR',
    role: 'Dept Manager',
    department: 'Engineering',
    departmentId: 'dept-nova-eng',
    team: 'Platform Squad',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    status: 'active',
    joinedAt: '2024-05-11',
    lastActive: '1h ago',
    lastLogin: 'Today, 7:55 AM',
    manager: 'Ahsan Taqweem',
    phone: '+971 52 889 4411',
    location: 'Sharjah, UAE',
    tasksAssigned: 31,
    projects: 5,
    activity: [
      act('project', 'Created project', 'API Gateway v2', 'Yesterday'),
      act('task', 'Assigned task', 'Dashboard charts · Lina Noor', 'Yesterday'),
    ],
  },
  {
    id: 'usr-lina',
    name: 'Lina Noor',
    email: 'lina@novatech.io',
    initials: 'LN',
    role: 'Team Lead',
    department: 'Design',
    departmentId: 'dept-nova-design',
    team: 'Design Systems',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    status: 'active',
    joinedAt: '2024-06-20',
    lastActive: '45m ago',
    lastLogin: 'Today, 9:02 AM',
    manager: 'Sara Khan',
    phone: '+971 54 100 7788',
    location: 'Dubai, UAE',
    tasksAssigned: 19,
    projects: 4,
    activity: [
      act('task', 'Updated task', 'Command palette polish', '45m ago'),
      act('email', 'Sent digest', 'Weekly design critique notes', 'Yesterday'),
    ],
  },
  {
    id: 'usr-omar',
    name: 'Omar Farooq',
    email: 'omar@novatech.io',
    initials: 'OF',
    role: 'Employee',
    department: 'Engineering',
    departmentId: 'dept-nova-eng',
    team: 'Platform Squad',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    status: 'invited',
    joinedAt: '2026-07-20',
    lastActive: '—',
    lastLogin: 'Never',
    manager: 'M. Raza',
    phone: '',
    location: 'Remote',
    tasksAssigned: 0,
    projects: 0,
    activity: [
      act('invite', 'Invite sent', 'Pending acceptance', '6d ago'),
      act('email', 'Reminder emailed', 'Join NovaTech Solutions', '2d ago'),
    ],
  },
  {
    id: 'usr-hira',
    name: 'Hira Ali',
    email: 'hira@novatech.io',
    initials: 'HA',
    role: 'HR',
    department: 'HR',
    departmentId: 'dept-nova-hr',
    team: 'People Ops',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    status: 'active',
    joinedAt: '2024-08-01',
    lastActive: '3h ago',
    lastLogin: 'Today, 10:20 AM',
    manager: 'Ahsan Taqweem',
    phone: '+971 56 333 9090',
    location: 'Abu Dhabi, UAE',
    tasksAssigned: 7,
    projects: 2,
    activity: [
      act('task', 'Closed ticket', 'Onboarding checklist Q3', '3h ago'),
    ],
  },
  {
    id: 'usr-nadia',
    name: 'Nadia Rehman',
    email: 'nadia@harborlogistics.com',
    initials: 'NR',
    role: 'Org Owner',
    department: 'Executive',
    departmentId: 'dept-harbor-exec',
    team: 'Leadership',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Logistics',
    status: 'active',
    joinedAt: '2023-11-02',
    lastActive: '5h ago',
    lastLogin: 'Yesterday, 6:12 PM',
    manager: null,
    phone: '+92 300 111 2233',
    location: 'Karachi, PK',
    tasksAssigned: 9,
    projects: 11,
    activity: [
      act('project', 'Reviewed report', 'Weekly capacity report', '5h ago'),
      act('login', 'Signed in', 'Edge · Karachi', 'Yesterday'),
    ],
  },
  {
    id: 'usr-bilal',
    name: 'Bilal Ahmed',
    email: 'bilal@harborlogistics.com',
    initials: 'BA',
    role: 'Org Admin',
    department: 'Operations',
    departmentId: 'dept-harbor-ops',
    team: 'Hub Ops',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Logistics',
    status: 'active',
    joinedAt: '2023-12-15',
    lastActive: '2h ago',
    lastLogin: 'Today, 8:00 AM',
    manager: 'Nadia Rehman',
    phone: '+92 321 444 5566',
    location: 'Karachi, PK',
    tasksAssigned: 22,
    projects: 7,
    activity: [
      act('task', 'Published update', 'Cold Chain department setup', '2d ago'),
    ],
  },
  {
    id: 'usr-usman',
    name: 'Usman Tariq',
    email: 'usman@harborlogistics.com',
    initials: 'UT',
    role: 'Employee',
    department: 'Operations',
    departmentId: 'dept-harbor-ops',
    team: 'Fleet',
    organizationId: 'org-harbor',
    organizationName: 'Harbor Logistics',
    status: 'suspended',
    joinedAt: '2024-02-10',
    lastActive: '3 weeks ago',
    lastLogin: 'Jun 30, 2026',
    manager: 'Bilal Ahmed',
    phone: '+92 333 777 8899',
    location: 'Hyderabad, PK',
    tasksAssigned: 4,
    projects: 1,
    activity: [
      act('permission', 'Account suspended', 'Policy review in progress', '3 weeks ago'),
    ],
  },
  {
    id: 'usr-amna',
    name: 'Dr. Amna Siddiqui',
    email: 'amna@pulsehealth.care',
    initials: 'AS',
    role: 'Org Owner',
    department: 'Clinical',
    departmentId: 'dept-pulse-clinical',
    team: 'Clinical Ops',
    organizationId: 'org-pulse',
    organizationName: 'Pulse Health Group',
    status: 'active',
    joinedAt: '2024-07-18',
    lastActive: '4h ago',
    lastLogin: 'Today, 7:30 AM',
    manager: null,
    phone: '+92 342 555 1212',
    location: 'Lahore, PK',
    tasksAssigned: 6,
    projects: 5,
    activity: [
      act('login', 'Signed in', 'iPad · Clinic A', '4h ago'),
    ],
  },
  {
    id: 'usr-kamran',
    name: 'Kamran Shah',
    email: 'kamran@pulsehealth.care',
    initials: 'KS',
    role: 'Org Admin',
    department: 'IT',
    departmentId: 'dept-pulse-it',
    team: 'Health IT',
    organizationId: 'org-pulse',
    organizationName: 'Pulse Health Group',
    status: 'active',
    joinedAt: '2024-07-25',
    lastActive: '1d ago',
    lastLogin: 'Yesterday, 9:45 AM',
    manager: 'Dr. Amna Siddiqui',
    phone: '+92 300 888 3344',
    location: 'Lahore, PK',
    tasksAssigned: 15,
    projects: 3,
    activity: [
      act('permission', 'Enabled MFA', 'All admin accounts', '1d ago'),
    ],
  },
  {
    id: 'usr-imran',
    name: 'Imran Qureshi',
    email: 'imran@ledgerco.finance',
    initials: 'IQ',
    role: 'Org Owner',
    department: 'Finance',
    departmentId: 'dept-ledger-finance',
    team: 'Advisory',
    organizationId: 'org-ledger',
    organizationName: 'Ledger & Co.',
    status: 'active',
    joinedAt: '2025-01-09',
    lastActive: '6h ago',
    lastLogin: 'Today, 11:05 AM',
    manager: null,
    phone: '+92 51 555 0199',
    location: 'Islamabad, PK',
    tasksAssigned: 11,
    projects: 4,
    activity: [
      act('task', 'Closed checklist', 'Q2 audit items', '3h ago'),
    ],
  },
  {
    id: 'usr-mehwish',
    name: 'Mehwish Rauf',
    email: 'mehwish@ledgerco.finance',
    initials: 'MR',
    role: 'Dept Manager',
    department: 'Finance',
    departmentId: 'dept-ledger-finance',
    team: 'Compliance',
    organizationId: 'org-ledger',
    organizationName: 'Ledger & Co.',
    status: 'active',
    joinedAt: '2025-01-20',
    lastActive: '30m ago',
    lastLogin: 'Today, 8:15 AM',
    manager: 'Imran Qureshi',
    phone: '+92 51 555 0200',
    location: 'Islamabad, PK',
    tasksAssigned: 17,
    projects: 3,
    activity: [
      act('email', 'Sent report', 'Compliance weekly digest', '30m ago'),
    ],
  },
  {
    id: 'usr-zain',
    name: 'Zain Malik',
    email: 'zain@ledgerco.finance',
    initials: 'ZM',
    role: 'Guest',
    department: 'Finance',
    departmentId: 'dept-ledger-finance',
    team: 'Audit',
    organizationId: 'org-ledger',
    organizationName: 'Ledger & Co.',
    status: 'invited',
    joinedAt: '2026-07-18',
    lastActive: '—',
    lastLogin: 'Never',
    manager: 'Mehwish Rauf',
    phone: '',
    location: 'Remote',
    tasksAssigned: 0,
    projects: 0,
    activity: [
      act('invite', 'Invite pending', 'Guest auditor access', '8d ago'),
    ],
  },
  {
    id: 'usr-fahad',
    name: 'Fahad Mirza',
    email: 'fahad@summitretail.com',
    initials: 'FM',
    role: 'Org Owner',
    department: 'Executive',
    departmentId: 'dept-summit-exec',
    team: 'Leadership',
    organizationId: 'org-summit',
    organizationName: 'Summit Retail Group',
    status: 'active',
    joinedAt: '2022-09-14',
    lastActive: '12m ago',
    lastLogin: 'Today, 6:50 AM',
    manager: null,
    phone: '+966 50 111 2233',
    location: 'Riyadh, SA',
    tasksAssigned: 14,
    projects: 16,
    activity: [
      act('project', 'Reviewed board', 'Ramadan campaign', 'Yesterday'),
      act('login', 'Signed in', 'Chrome · Riyadh', '12m ago'),
    ],
  },
  {
    id: 'usr-noor',
    name: 'Noor Hassan',
    email: 'noor@summitretail.com',
    initials: 'NH',
    role: 'Org Admin',
    department: 'Marketing',
    departmentId: 'dept-summit-mkt',
    team: 'Merchandising',
    organizationId: 'org-summit',
    organizationName: 'Summit Retail Group',
    status: 'active',
    joinedAt: '2023-01-08',
    lastActive: '2h ago',
    lastLogin: 'Today, 9:30 AM',
    manager: 'Fahad Mirza',
    phone: '+966 55 444 7788',
    location: 'Jeddah, SA',
    tasksAssigned: 28,
    projects: 9,
    activity: [
      act('task', 'Assigned campaign', 'E-commerce Q3 launch', '2h ago'),
    ],
  },
  {
    id: 'usr-saima',
    name: 'Prof. Saima Riaz',
    email: 'saima@canvasedu.org',
    initials: 'SR',
    role: 'Org Owner',
    department: 'Executive',
    departmentId: 'dept-canvas-exec',
    team: 'Academics',
    organizationId: 'org-canvas',
    organizationName: 'Canvas Education',
    status: 'active',
    joinedAt: '2024-10-30',
    lastActive: '8h ago',
    lastLogin: 'Yesterday, 4:20 PM',
    manager: null,
    phone: '+92 91 555 0101',
    location: 'Peshawar, PK',
    tasksAssigned: 5,
    projects: 6,
    activity: [
      act('project', 'Published pack', 'Term 2 syllabus', '8h ago'),
    ],
  },
  {
    id: 'usr-haris',
    name: 'Haris Naveed',
    email: 'haris@canvasedu.org',
    initials: 'HN',
    role: 'Team Lead',
    department: 'Support',
    departmentId: 'dept-canvas-support',
    team: 'Partnerships',
    organizationId: 'org-canvas',
    organizationName: 'Canvas Education',
    status: 'active',
    joinedAt: '2024-11-12',
    lastActive: '1h ago',
    lastLogin: 'Today, 10:00 AM',
    manager: 'Prof. Saima Riaz',
    phone: '+92 91 555 0102',
    location: 'Peshawar, PK',
    tasksAssigned: 13,
    projects: 4,
    activity: [
      act('invite', 'Added partners', '2 school districts', '3d ago'),
    ],
  },
  {
    id: 'usr-ayesha',
    name: 'Ayesha Bukhari',
    email: 'ayesha@orbitmedia.lab',
    initials: 'AB',
    role: 'Org Owner',
    department: 'Marketing',
    departmentId: 'dept-orbit-mkt',
    team: 'Creative',
    organizationId: 'org-orbit',
    organizationName: 'Orbit Media Labs',
    status: 'suspended',
    joinedAt: '2023-05-21',
    lastActive: '2 weeks ago',
    lastLogin: 'Jul 10, 2026',
    manager: null,
    phone: '+1 415 555 0199',
    location: 'Remote',
    tasksAssigned: 2,
    projects: 1,
    activity: [
      act('permission', 'Workspace inactive', 'Archive mode enabled', '2 weeks ago'),
    ],
  },
  {
    id: 'usr-guest',
    name: 'Jordan Lee',
    email: 'jordan.lee@external.consult',
    initials: 'JL',
    role: 'Guest',
    department: 'Product',
    departmentId: 'dept-nova-product',
    team: 'External Advisors',
    organizationId: 'org-nova',
    organizationName: 'NovaTech Solutions',
    status: 'invited',
    joinedAt: '2026-07-22',
    lastActive: '—',
    lastLogin: 'Never',
    manager: 'Sara Khan',
    phone: '',
    location: 'Remote',
    tasksAssigned: 0,
    projects: 1,
    activity: [
      act('invite', 'Guest invite sent', 'Read-only product access', '4d ago'),
    ],
  },
];

export function getUserById(id) {
  return USERS.find((u) => u.id === id) || null;
}

export function filterUsers(
  list,
  { query = '', role = 'all', department = 'all', status = 'all', organizationId = 'all' } = {}
) {
  const q = query.trim().toLowerCase();
  return list.filter((user) => {
    if (role !== 'all' && user.role !== role) return false;
    if (department !== 'all' && user.department !== department) return false;
    if (status !== 'all' && user.status !== status) return false;
    if (organizationId !== 'all' && user.organizationId !== organizationId) return false;
    if (!q) return true;
    const hay = [user.name, user.email, user.department, user.organizationName, user.role]
      .join(' ')
      .toLowerCase();
    return hay.includes(q);
  });
}

export function formatJoinedDate(iso) {
  try {
    return new Date(iso).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  } catch {
    return iso;
  }
}
